import type { MetadataRoute } from "next";

import { CALCULATORS } from "@/features/calculators/registry";
import { LOCALES } from "@/i18n/types";
import { getArticleSlugs, getContentUpdatedDates, getLegalSlugs } from "@/features/wiki/content";
import { getChangelogLastUpdated } from "@/features/changelog/content";
import { absoluteUrl } from "@/shared/seo/site";
import { localizedPath } from "@/shared/seo/seo";

/**
 * Dynamic sitemap. Emits ONE entry per page with its locale variants in
 * `alternates.languages` (hreflang es/en + x-default), instead of listing es and en
 * as separate URLs. Private routes and routes with no indexing value
 * (portfolio, login, callbacks, gracias, oauth) are left out on purpose.
 *
 * The sources are the same ones that feed the app: the calculator registry and
 * the wiki/legal Markdown files, so adding content updates the sitemap without
 * touching this file.
 *
 * `lastModified` is only emitted when there is a REAL revision date (`updated` in
 * the article frontmatter, `updatedAt` in the legal one). Every entry used to get
 * `new Date()`: a `lastmod` that changes on every crawl carries no information and
 * search engines end up ignoring it, so it is better to omit it where it is unknown.
 * Calculators and fixed pages carry no date because their content is generated by
 * code, not by a file with its own history.
 */
export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const [esArticles, enArticles, esLegal, enLegal, articleDates, legalDates, changelogDate] = await Promise.all([
    getArticleSlugs("es"),
    getArticleSlugs("en"),
    getLegalSlugs("es"),
    getLegalSlugs("en"),
    getContentUpdatedDates("wiki"),
    getContentUpdatedDates("legal"),
    getChangelogLastUpdated(),
  ]);

  const articleSlugs = [...new Set([...esArticles, ...enArticles])].sort();
  const legalSlugs = [...new Set([...esLegal, ...enLegal])].sort();

  /** One entry with its canonical (es) URL and the full hreflang map. */
  const entry = (
    path: string,
    priority: number,
    changeFrequency: MetadataRoute.Sitemap[number]["changeFrequency"],
    lastModified?: string,
  ): MetadataRoute.Sitemap[number] => {
    const languages: Record<string, string> = {};
    for (const locale of LOCALES) {
      languages[locale] = absoluteUrl(localizedPath(locale, path));
    }
    languages["x-default"] = absoluteUrl(localizedPath("es", path));
    return {
      url: absoluteUrl(localizedPath("es", path)),
      // The whole key is omitted when there is no reliable date (see header).
      ...(lastModified ? { lastModified } : {}),
      changeFrequency,
      priority,
      alternates: { languages },
    };
  };

  return [
    entry("/", 1, "weekly"),
    entry("/calculadoras", 0.9, "weekly"),
    entry("/aprende", 0.8, "weekly"),
    // Unlike the calculators, this page DOES have a real content date (the latest
    // release), so `lastmod` is emitted.
    entry("/novedades", 0.5, "weekly", changelogDate),
    entry("/sobre-mi", 0.3, "yearly"),
    ...CALCULATORS.map((c) => entry(`/calculadoras/${c.slug}`, 0.8, "monthly")),
    ...articleSlugs.map((slug) => entry(`/aprende/${slug}`, 0.7, "monthly", articleDates.get(slug))),
    ...legalSlugs.map((slug) => entry(`/legal/${slug}`, 0.2, "yearly", legalDates.get(slug))),
  ];
}
